import Link from 'next/link';
export const metadata={title:'Reading terms & credits · Quran Sanity Agent'};
export default function Terms(){return <main className="policy-page">
 <Link href="/">← Research workspace · العودة للبحث</Link>
 <h1>Reading terms & source credits</h1>
 <p>This workspace helps readers find scripture and inspect commentary. AI reading notes are separate from original source text. It is not a fatwa service, hadith authentication service, or a substitute for qualified scholarly review.</p>
 <h2>Sources</h2><p>Arabic Quran text: <a href="https://tanzil.net/docs/text_license">Tanzil Uthmani 1.1</a>. Displayed scripture is not generated by AI. The stored English rendering exactly matches Saheeh International, Quran.com resource20; source identity does not itself establish redistribution permission or a specific printed edition.</p>
 <p>Imported commentary metadata and copies include Quran.com / Quran Foundation and the user-provided Tabattal snapshots. Curated primary excerpts link to their original tafsir providers. Retain source attribution and consult <a href="https://api-docs.quran.com/legal/developer-terms/">Quran Foundation developer terms</a> and each source&apos;s permissions. Do not treat application access as a license to redistribute the underlying dataset.</p>
 <h2>Evidence limits</h2><p>A citation identifies where a passage was retrieved; it does not prove every paraphrase, narration or classification correct. Some editions lack explicit verse anchors. Automated quote and support checks are not specialist endorsement. Unsupported or rejected notes leave original excerpts or a stated evidence gap.</p>
 <section dir="rtl" lang="ar"><h2>إرشادات القراءة</h2><p>المنصة للبحث ومراجعة المصادر، وليست جهة فتوى أو تصحيح أسانيد. القراءة بمساعدة الذكاء الاصطناعي منفصلة عن النص الأصلي. افحص الاقتباس وسياقه، واستعن بمتخصص عند الحاجة. وجود المصدر لا يمنح تلقائيًا إذن إعادة توزيع بياناته.</p></section>
 <p>Report source or attribution corrections to <a href="mailto:sanity@omar-afifi.com">sanity@omar-afifi.com</a>, including the displayed source ID and the correction evidence.</p>
 <Link href="/privacy">Privacy</Link>
 </main>}
